version: '2'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: 'unless-stopped'
    ports:
      - '9639:80'
    networks:
      - snic-congress
    volumes:
      - partners:/usr/src/app/data/partners
      - speakers:/usr/src/app/data/speakers
      - barcodes:/usr/src/app/data/barcodes
  backend:
    build: ./backend
    container_name: backend
    restart: 'unless-stopped'
    networks:
      - snic-congress
    volumes:
      - partners:/usr/src/app/data/partners
      - speakers:/usr/src/app/data/speakers
      - barcodes:/usr/src/app/data/barcodes
    environment:
      - NODE_ENV=production
      - PORT=3001
      - USE_HTTPS=false
      - SERVER_HOST=localhost:9639
      - TZ=Europe/Amsterdam
      - TYPEORM_CONNECTION=mysql
      - TYPEORM_HOST=db
      - TYPEORM_PORT=3306
      - TYPEORM_DATABASE=snic2024
      - TYPEORM_USERNAME=svc-sustainabilit
      - TYPEORM_PASSWORD=
      - TYPEORM_SYNCHRONIZE=true
      - TYPEORM_LOGGING=false
      - SESSION_SECRET=Snic2024
      - SMTP_USERNAME=noreply@snic.nl
      - SMTP_PASSWORD=
      - URL=https://snic-sustainabilit.nl
  db:
    image: mysql:latest
    container_name: db
    restart: 'unless-stopped'
    networks:
      - snic-congress
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=snic2024
      - MYSQL_USER=svc-celerit
      - MYSQL_PASSWORD=
    volumes:
      - db_data:/var/lib/mysql

volumes:
  partners:
    driver: local
  speakers:
    driver: local
  barcodes:
    driver: local
  db_data:
    driver: local

networks:
  snic-congress:
    driver: bridge
