apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "snic.fullname" . }}-uploads
spec:
  storageClassName: ceph-filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 19Gi
