apiVersion: v1
kind: Service
metadata:
  name: {{ include "snic.fullname" . }}-backend
  labels:
    {{- include "snic.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "snic.selectorLabels.backend" . | nindent 4 }}
